--CREATE DATABASE FlashCards
--GO;

--USE FlashCards
--GO;

CREATE TABLE tblCARD (
CardID INT IDENTITY(1, 1) PRIMARY KEY,
CardName VARCHAR(50) NOT NULL,
CardDescr VARCHAR(500) NULL
)

CREATE TABLE tblDECK (
DeckID INT IDENTITY(1, 1) PRIMARY KEY,
DeckName VARCHAR(100),
DeckDescr VARCHAR(500),
)

CREATE TABLE tblSUBJECT (
SubjectID INT IDENTITY(1, 1) PRIMARY KEY,
SubjectName VARCHAR(50),
SubjectDescr VARCHAR(500)
)

CREATE TABLE tblOWNER (
OwnerID INT IDENTITY(1, 1) PRIMARY KEY,
OwnerFname VARCHAR(50),
OwnerLname VARCHAR(50),
OwnerDescr VARCHAR(500),
)

CREATE TABLE tblDECK_TAG (
DeckTagID INT IDENTITY(1, 1) PRIMARY KEY,
)

CREATE TABLE tblTAG (
TagID INT IDENTITY(1, 1) PRIMARY KEY,
TagName VARCHAR(50),
TagDescr VARCHAR(500),
)

CREATE TABLE tblSIDE (
SideID INT IDENTITY(1, 1) PRIMARY KEY,
SideName VARCHAR(5),
SideDescr VARCHAR(500),
)

CREATE TABLE tblASSIGNMENT_CARD (
AssignmentCardID INT IDENTITY(1, 1) PRIMARY KEY,
BeginDateTime TIMESTAMP,  -- TIMESTAMP - format: YYYY-MM-DD HH:MM:SS
EndDateTime DATETIME,    -- TIMESTAMP - format: YYYY-MM-DD HH:MM:SS
)

CREATE TABLE tblASSIGNMENT (
AssignmentID INT IDENTITY(1, 1) PRIMARY KEY,
)

CREATE TABLE tblSTUDENT (
StudentFname VARCHAR(50) NOT NULL,
StudentLname VARCHAR(50) NOT NULL,
BirthDate TIMESTAMP NULL,
email VARCHAR(100),
)

CREATE TABLE tblMEDIA_CARD (
MediaCardID INT IDENTITY(1, 1) PRIMARY KEY,
--Img LONGBLOB NULL, -- Image, Instance of Size(MB) We had Img
Words TEXT NULL
)

CREATE TABLE tblMEDIA (
MediaID INT IDENTITY(1, 1) PRIMARY KEY,
MediaName VARCHAR(30) NOT NULL,
MediaDescr VARCHAR(500) NULL,
)

CREATE TABLE tblNOTE (
NoteID INT IDENTITY(1, 1) PRIMARY KEY,
NoteDate TIMESTAMP,
)

CREATE TABLE tblREVIEW (
ReviewID INT IDENTITY(1, 1) PRIMARY KEY,
ReviewDate TIMESTAMP,
)

CREATE TABLE tblRATING (
RatingID INT IDENTITY(1, 1) PRIMARY KEY,
RatingName VARCHAR(50) NULL,
)

CREATE TABLE tblINTERVAL (
IntervalID INT IDENTITY(1, 1) PRIMARY KEY,
DueDate TIMESTAMP NOT NULL,  -- After this time u should repeat that card
--- I DON'T NEED IntervalName  AND IntervalDescr
)


-------------------
-- ALTER TABLES
--------------------
ALTER TABLE tblDECK
ADD SubjectID INT NULL,
	OwnerID   INT NULL;
	GO
ALTER TABLE tblDECK
ADD CONSTRAINT FK_DECK_SUBJECT
	FOREIGN KEY (SubjectID)
	REFERENCES tblSUBJECT(SubjectID),
    CONSTRAINT FK_DECK_OWNER
	FOREIGN KEY (OwnerID)
	REFERENCES tblOWNER(OwnerID);


ALTER TABLE tblDECT_TAG
ADD CONSTRAINT FK_DectTag_DECK
	FOREIGN KEY (DeckID)
	REFERENCES tblDECK(DeckID),
	CONSTRAINT FK_DeckTag_Tag
	FOREIGN KEY (TagID)
	REFERENCES tblTAG(TagID)
























